### ISSUE TITLE
Model transaction

### ISSUE THREAD

**Issue by AbdullahKadad** [Funance-Tracker/finance-manager#2]

**Comment by AbdullahKadad** [comment]
def: return balance of user 
def: add new debt for user 
def: add to balance of the user 
def: new transaction of the user and (decrease the amount from the balance)

**Comment by Raghadkatout08** [comment]
Raghad: 
-> def: return balance of user
-> def: add to balance of the user

Balqees: 
-> def: add new debt for user
-> def: new transaction of the user and (decrease the amount from the balance)
